ALTER TABLE ugyfel AUTO_INCREMENT = 1;
ALTER TABLE maganszemely AUTO_INCREMENT = 1;
ALTER TABLE msafa AUTO_INCREMENT = 1;
ALTER TABLE egyenivallalkozo AUTO_INCREMENT = 1;
ALTER TABLE evafa AUTO_INCREMENT = 1;
ALTER TABLE tarsasag AUTO_INCREMENT = 1;
ALTER TABLE tafa AUTO_INCREMENT = 1